=== meghamohadikar/BACKBASE/UBP/dione/dione-specification/src/main/resources/schemas/Person.json
{
      "$schema": "http://json-schema.org/draft-04/schema#",
      "id": "Person",
      "title": "Person",
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "personNb": {
          "type": "integer",
          "format": "int64"
        },
        "login": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "companyCode": {
          "type": "string"
        },
        "isAnonymous": {
          "type": "boolean"
        },
        "phones": {
          "description": "",
          "type": "array",
          "items": {
            "id": "Phone",
            "title": "Phone",
            "type": "object",
            "properties": {
              "number": {
                "type": "string"
              },
              "type": {
                "type": "string"
              }
            }
          }
        },
        "roleAndSignatures": {
          "description": "",
          "type": "array",
          "items": {
            "id": "RoleAndSignature",
            "title": "RoleAndSignature",
            "type": "object",
            "properties": {
              "signature": {
                "type": "string"
              },
              "role": {
                "type": "string"
              }
            }
          }
        }
      }
    }

=== meghamohadikar/BACKBASE/UBP/dione/data/personJson.json
[
  {
    "id": 1478,
    "personNb": 1,
    "login": "machin",
    "firstName": "fran",
    "lastName": "truc",
    "companyCode": "FR201819700",
    "isAnonymous": true,
    "phones": [
      {
        "number": "+33688256482",
        "type": "string"
      }
    ],
    "roleAndSignatures": [
      {
        "signature": "signature",
        "role": "role"
      }
    ]
  },
  {
    "id": 2019,
    "personNb": 5,
    "login": "perso2",
    "firstName": "Akrem",
    "lastName": "KALIMBO",
    "companyCode": "EN214564800",
    "isAnonymous": true,
    "phones": [
      {
        "number": "+33788251624",
        "type": "string"
      }
    ],
    "roleAndSignatures": [
      {
        "signature": "signature",
        "role": "role"
      }
    ]
  }
]
