=== meghamohadikar/BACKBASE/UBP/pms/pma-signers-specification/src/main/resources/schemas/sample_pma_signers.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "ApiSignerEntity",
  "title": "ApiSignerEntity",
  "type": "object",
  "properties": {
    "company": {
      "type": "string"
    },
    "tiersNumber": {
      "type": "string"
    },
    "personName": {
      "type": "string"
    },
    "personSurname": {
      "type": "string"
    },
    "personBirthdate": {
      "format": "date-time",
      "type": "string"
    },
    "portfolioCode": {
      "type": "string"
    },
    "personId": {
      "format": "int32",
      "type": "integer"
    },
    "hasSignaturePower": {
      "type": "boolean"
    },
    "homeCountry": {
      "type": "string"
    },
    "personType": {
      "type": "string"
    },
    "personRoles": {
      "type": "string"
    },
    "personSignature": {
      "type": "string"
    },
    "isRepresentative": {
      "type": "boolean"
    },
    "nameMifidCat": {
      "type": "string"
    },
    "knowledge": {
      "format": "double",
      "type": "number"
    },
    "experience": {
      "format": "double",
      "type": "number"
    }
  }
}

=== meghamohadikar/BACKBASE/UBP/pms/data/sample_pma_signers.json
[
  {
    "company": "001",
    "tiersNumber": "6045960",
    "personName": "pierre",
    "personSurname": "martin",
    "personBirthdate": "2017-01-02 05:30:00",
    "portfolioCode": "PTF",
    "personId": 123,
    "hasSignaturePower": true,
    "homeCountry": "FR",
    "personType": "VIP",
    "personRoles": "RM",
    "personSignature": "SIGNED",
    "isRepresentative": true,
    "nameMifidCat": "MIFID1",
    "knowledge": 20.2,
    "experience": 30.3
  }
]
